# pre-commit run --all-files
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
-   repo: https://gitlab.com/pycqa/flake8
    rev: ''
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: .venv-dev/bin/pytest
        language: system
        pass_filenames: false
        always_run: true