# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy

on:
  push:
    branches: [ master ]
    tags: 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Copy .env
      shell: bash
      env:
        ENV: ${{ secrets.ENV }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
      run: |
        mkdir .ssh
        echo "$KEY" > .ssh/id_rsa
        tail .ssh/id_rsa
        chmod 700 .ssh/id_rsa
        echo "$ENV" > .env
        scp -o "StrictHostKeyChecking=no" -i ".ssh/id_rsa" .env "$USERNAME@$HOST:~/projects/notification_svc/notification_svc/"
          
